import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '@/components/navbar.component'
import AuthProvider from '@/components/auth-provider.component'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="h-full">
            <AuthProvider>
                <body className="h-full bg-gradient-to-b from-[#26212F] to-[#3E2844]">
                    <NavBar />
                    {children}
                </body>
            </AuthProvider>
        </html>
    )
}
